sudo: required
services:
  - docker

before_install:
  - docker build -t complex-fab -f ./client/Dockerfile.dev ./client

install:
  - npm rebuild node-sass

script:
  - docker run complex-fab npm run test:unit -- --coverage

after_success:
  - docker build -t nascal3/complex-client ./client
  - docker build -t nascal3/complex-nginx ./nginx
  - docker build -t nascal3/complex-server ./server
  - docker build -t nascal3/complex-worker ./worker

  #  Login docker CLI
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD" docker.io
  #  Push images into docker hub
  - docker push nascal3/complex-client
  - docker push nascal3/complex-nginx
  - docker push nascal3/complex-server
  - docker push nascal3/complex-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: complex-fab
  env: ComplexFab-env
  bucket_name: elasticbeanstalk-us-east-2-511328767950
  bucket_path: docker-complex-fab
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
