sudo: required
services:
  - docker

before_install:
  -  docker build -t complex-fab -f ./client/Dockerfile.dev ./client

script:
  - docker run complex-fab npm run test:unit -- --coverage

after_success:
  - docker build -t client ./client
  - docker build -t ngnix ./ngnix
  - docker build -t server ./server
  - docker build -t worker ./worker

  #  Login docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password--stdin
  #  Push images into docker hub
  - -docker push client
  - -docker push ngnix
  - -docker push server
  - -docker push worker



